"use client";
import { FormEvent, useState } from "react";
import { createClient } from "../lib/supabase/client";

type Settings={business_name?:string|null;business_description?:string|null;services?:string[]|null;tone_of_voice?:string|null;preferred_language?:string|null;qualification_questions?:string[]|null;custom_instructions?:string|null;handoff_rules?:string|null;ai_enabled?:boolean|null};
export default function AISettingsForm({tenantId,initial}:{tenantId:string;initial:Settings|null}){
  const [saved,setSaved]=useState(false); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({business_name:initial?.business_name??"",business_description:initial?.business_description??"",services:(initial?.services??[]).join("\n"),tone_of_voice:initial?.tone_of_voice??"",preferred_language:initial?.preferred_language??"",qualification_questions:(initial?.qualification_questions??[]).join("\n"),custom_instructions:initial?.custom_instructions??"",handoff_rules:initial?.handoff_rules??"",ai_enabled:initial?.ai_enabled??true});
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setSaved(false);const payload={tenant_id:tenantId,business_name:form.business_name,business_description:form.business_description,services:form.services.split("\n").map(x=>x.trim()).filter(Boolean),tone_of_voice:form.tone_of_voice,preferred_language:form.preferred_language,qualification_questions:form.qualification_questions.split("\n").map(x=>x.trim()).filter(Boolean),custom_instructions:form.custom_instructions,handoff_rules:form.handoff_rules,ai_enabled:form.ai_enabled,updated_at:new Date().toISOString()};const {error}=await createClient().from("tenant_ai_settings").upsert(payload,{onConflict:"tenant_id"});setSaving(false);if(!error)setSaved(true);}
  const set=(key:string,value:any)=>setForm(prev=>({...prev,[key]:value}));
  return <form className="grid" onSubmit={submit}><div className="card grid"><label>Business name<input className="input" value={form.business_name} onChange={e=>set("business_name",e.target.value)}/></label><label>Business description<textarea className="input" rows={4} value={form.business_description} onChange={e=>set("business_description",e.target.value)}/></label><label>Services — one per line<textarea className="input" rows={5} value={form.services} onChange={e=>set("services",e.target.value)}/></label><label>Tone of voice<input className="input" value={form.tone_of_voice} onChange={e=>set("tone_of_voice",e.target.value)}/></label><label>Preferred language<input className="input" value={form.preferred_language} onChange={e=>set("preferred_language",e.target.value)}/></label><label>Qualification questions — one per line<textarea className="input" rows={5} value={form.qualification_questions} onChange={e=>set("qualification_questions",e.target.value)}/></label><label>Custom AI instructions<textarea className="input" rows={6} value={form.custom_instructions} onChange={e=>set("custom_instructions",e.target.value)}/></label><label>Handoff rules<textarea className="input" rows={4} value={form.handoff_rules} onChange={e=>set("handoff_rules",e.target.value)}/></label><label><input type="checkbox" checked={form.ai_enabled} onChange={e=>set("ai_enabled",e.target.checked)}/> AI enabled</label><button className="btn" disabled={saving}>{saving?"Saving...":"Save settings"}</button>{saved&&<div>Saved.</div>}</div></form>;
}
